apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api-monitor
  namespace: apps
spec:
  selector:
    matchLabels:
      app: backend-api
  endpoints:
  - port: "8081"       # <-- string now
    path: /metrics
    interval: 15s

