apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-gmail-config
  namespace: monitor
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '2244deborah@gmail.com'
      smtp_auth_username: '2244deborah@gmail.com'
      smtp_auth_password: ''
    route:
      receiver: 'gmail'
    receivers:
      - name: 'gmail'
        email_configs:
          - to: '2244deborah@gmail.com'
